ALTER TABLE stars ADD COLUMN situation TEXT NOT NULL;
ALTER TABLE stars ADD COLUMN task TEXT NOT NULL;
ALTER TABLE stars ADD COLUMN action TEXT;
ALTER TABLE stars ADD COLUMN result TEXT;

ALTER TABLE stars ADD favourite BOOLEAN DEFAULT false;
